import { chromium } from '@playwright/test';
import { createServer } from 'vite';
const server = await createServer({ server: { port: 0 }, logLevel: 'error' });
await server.listen();
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
await page.addInitScript(() => localStorage.setItem('mcnoose-wip-seen', '1'));
await page.goto(server.resolvedUrls!.local[0]);
await page.waitForSelector('html[data-printed="true"]');
await page.addStyleTag({ content: '.lil-gui { display: none !important }' });
await page.screenshot({ path: '/private/tmp/claude-501/-Users-nicyoung-source-play-mcnoose-dot-com/4a6e25ab-b31a-4465-8d11-f3cd8c59e3f7/scratchpad/look-full.png', fullPage: true, scale: 'css' });
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await page.waitForTimeout(400);
const s = (await page.locator('.skirting').boundingBox())!;
await page.screenshot({ path: '/private/tmp/claude-501/-Users-nicyoung-source-play-mcnoose-dot-com/4a6e25ab-b31a-4465-8d11-f3cd8c59e3f7/scratchpad/look-sk.png', clip: { x: 400, y: s.y - 40, width: 400, height: 900 - s.y + 40 } });
const r = (await page.locator('.rail').boundingBox())!;
await browser.close(); await server.close();
